"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[323],{65273:function(t,e,s){s.d(e,{Z:function(){return g}});var h=s(62435),o=s(46837),l=s(8250),r=s(29671),a=s(20640),c=s.n(a),d=s(33862),v=s(1210),u=s(85093),m=s(10524),x=s(14079),i=s(49721),j=s.p+"static/logo.716e211f.png",f=`**RA** \r
in CUHKSZ.\r
\r
`,n=s(86074),g=function(){var N=function(S){S.preventDefault(),c()(i.email),o.ZP.success("Email copied to clipboard",1)};return(0,n.jsxs)("div",{className:"sidebar",children:[(0,n.jsxs)("div",{className:"profile",children:[(0,n.jsx)(l.C,{size:{xs:48,sm:64,md:80,lg:128,xl:160,xxl:200},src:j}),(0,n.jsxs)("div",{className:"info",children:[(0,n.jsx)("div",{className:"name",children:i.name}),(0,n.jsx)("div",{className:"shortInfo",children:(0,n.jsx)(r.U,{children:f})})]})]}),(0,n.jsxs)("div",{className:"link",children:[(0,n.jsxs)("div",{children:[(0,n.jsx)(d.Z,{className:"icon"}),i.location]}),(0,n.jsxs)("div",{children:[(0,n.jsx)(v.Z,{className:"icon"}),(0,n.jsx)("a",{href:i.github,children:"Github"})]}),(0,n.jsxs)("div",{children:[(0,n.jsx)(u.Z,{className:"icon"}),(0,n.jsx)("a",{href:i==null?void 0:i.twitter,children:"Twitter"})]}),(0,n.jsxs)("div",{children:[(0,n.jsx)(m.Z,{className:"icon"}),(0,n.jsx)("a",{onClick:N,href:"",children:"Email"})]}),(0,n.jsxs)("div",{children:[(0,n.jsx)(x.Z,{className:"icon"}),(0,n.jsx)("a",{href:i==null?void 0:i.googleScholar,children:"Google Scholar"})]})]})]})}},92041:function(t,e,s){s.r(e),s.d(e,{default:function(){return c}});var h=s(62435),o=`\r
Siyu Yu (Youth Yu)\r
received the B.S. and M.S. degree from [Guangxi University](https://www.gxu.edu.cn/), supervised by professor Ningjiang Chen. He is currently a research assistant in the School of Data Science with [The Chinese University of HongKong Shenzhen](https://www.cuhk.edu.cn/zh-hans), Shenzhen, China, supervised by professor [Pinjia He](https://scholar.google.com/citations?user=vg0moI0AAAAJ&hl=en&oi=sra). His research lies within Software Engineering, with special interests in software log analysis.\r
\r
\r
`,l=s(65273),r=s(29671),a=s(86074),c=function(){return(0,a.jsxs)("div",{className:"page",children:[(0,a.jsx)(l.Z,{}),(0,a.jsxs)("div",{className:"content",children:[(0,a.jsx)("div",{className:"title",children:"About Me"}),(0,a.jsx)("div",{className:"markdown",children:(0,a.jsx)(r.U,{children:o})})]})]})}},49721:function(t){t.exports=JSON.parse('{"name":"Siyu Yu","location":"ShenZhen, China","email":"gaiusyu6@gmail.com","github":"https://github.com/gaiusyu","twitter":"https://twitter.com/None","googleScholar":"https://scholar.google.com/citations?user=PBRCSToAAAAJ&hl=en&oi=sra","showBar":["aboutme","publications","awards","services","cv"]}')}}]);
